In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 34])
np.square(a)

array([   1,    4, 1156])

In [3]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.square(m)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [4]:
a + m

array([[ 2,  4, 37],
       [ 5,  7, 40],
       [ 8, 10, 43]])

In [5]:
mmm = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
m @ m

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [6]:
np.sum(np.square(np.linspace(0, 1000000, 1000000)))

3.333335000001668e+17

In [7]:
import time
start = time.time()
print(np.sum(np.square(np.linspace(0, 1000000-1, 1000000))))
time_np = time.time() - start
print(time_np)

3.333328333335e+17
0.035524845123291016


In [8]:
start = time.time()
print(sum([x ** 2 for x in range(1000000)]))
time_py = time.time() - start
print(time_py)

333332833333500000
0.4787120819091797


In [9]:
time_py / time_np

13.475416437363258

In [10]:
%timeit np.sum(np.sum(np.square(np.linspace(0, 1000000, 1000000))))

6.42 ms ± 377 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%time np.sum(np.sum(np.square(np.linspace(0, 1000000, 1000000))))

CPU times: user 31.4 ms, sys: 3.09 ms, total: 34.4 ms
Wall time: 25.4 ms


3.333335000001668e+17